plugins {
    id "com.android.application"
}

android {
    namespace "com.glimmer.app"
    compileSdk 35

    defaultConfig {
        applicationId "com.glimmer.app"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "0.1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "com.vanniktech:android-image-cropper:4.7.0"
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
}
