param(
    [string]$RepoRoot = ""
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($RepoRoot)) {
    $RepoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
}

$outDir = Join-Path $RepoRoot "tc_ble_multi_sdk\vendor\pendant\build_info"
$outFile = Join-Path $outDir "app_build_info.h"
$gitSafeRepoRoot = $RepoRoot.Replace("\", "/")

function Get-GitText {
    param([string[]]$GitArgs, [string]$Fallback)
    $output = & git -c "safe.directory=$gitSafeRepoRoot" -c "core.excludesFile=" -C $RepoRoot @GitArgs 2>$null
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($output)) {
        return $Fallback
    }
    return ($output | Select-Object -First 1).Trim()
}

function Convert-ToCString {
    param([string]$Value)
    if ($null -eq $Value) {
        return ""
    }
    return $Value.Replace("\", "\\").Replace('"', '\"')
}

$sha = Get-GitText -GitArgs @("rev-parse", "--short=12", "HEAD") -Fallback "unknown"
$branch = Get-GitText -GitArgs @("rev-parse", "--abbrev-ref", "HEAD") -Fallback "unknown"
$status = & git -c "safe.directory=$gitSafeRepoRoot" -c "core.excludesFile=" -C $RepoRoot status --porcelain 2>$null
$dirty = if ($LASTEXITCODE -eq 0 -and $status) { 1 } else { 0 }
$desc = if ($dirty) { "$sha-dirty" } else { $sha }

$content = @"
#ifndef APP_BUILD_INFO_H_
#define APP_BUILD_INFO_H_

/* Auto-generated by tools/update_pendant_build_info.ps1. */

#define APP_BUILD_FW_NAME          "pendant"
#define APP_BUILD_FW_VERSION       "0.1.0-dev"
#define APP_BUILD_BOARD_NAME       "B85_DANGLE"
#define APP_BUILD_CHIP_NAME        "TLSR8258"

#define APP_BUILD_GIT_SHA          "$(Convert-ToCString $sha)"
#define APP_BUILD_GIT_BRANCH       "$(Convert-ToCString $branch)"
#define APP_BUILD_GIT_DIRTY        $dirty
#define APP_BUILD_GIT_DESC         "$(Convert-ToCString $desc)"

#define APP_BUILD_COMPILE_DATE     __DATE__
#define APP_BUILD_COMPILE_TIME     __TIME__

#endif
"@

if (!(Test-Path -LiteralPath $outDir)) {
    New-Item -ItemType Directory -Path $outDir | Out-Null
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
if ((Test-Path -LiteralPath $outFile)) {
    $old = [System.IO.File]::ReadAllText($outFile)
    if ($old -eq $content) {
        return
    }
}

[System.IO.File]::WriteAllText($outFile, $content, $utf8NoBom)
